# **블록 좌표화**

# **1층**

In [1]:
# 1층 A 블록

total_col = [1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,21,22]
층 = []
블록 = []
열 = []
넘버 = []

for num in total_col:
    if num <= 3 or num == 19 :
        chairs = range(1, 9 + 1)
    elif num <= 7 or num == 18:
        chairs = range(1, 10 + 1)
    elif num <= 11 or num == 16 or num == 17:
        chairs = range(1, 11 + 1)
    elif num <= 15:
        chairs = range(1, 12 + 1)
    elif num == 20:
        chairs = range(1, 8 + 1)
    else:
        chairs = range(1, 7 + 1)
        
    for i in chairs:
        층.append('1층')
        블록.append('A블록')
        열.append(str(num))
        넘버.append(str(i))

In [2]:
# 1층 B블록

total_col = list(range(1,22 + 1))

for num in total_col:
    if num == 1:
        chairs = range(1, 9 + 1)
    elif num <= 5:
        chairs = range(1, 10 + 1)
    elif num <= 10:
        chairs = range(1, 11 + 1)
    elif num <= 14:
        chairs = range(1, 12 + 1)
    elif num == 18:
        chairs = range(1, 13 + 1)
    else:
        chairs = range(1, 14 + 1)
        
    for i in chairs:
        층.append('1층')
        블록.append('B블록')
        열.append(str(num))
        넘버.append(str(i))

In [3]:
# 1층 C 블록

total_col = list(range(1,21 + 1))

for num in total_col:
    if num <= 5:
        chairs = range(1, 12 + 1)
    elif num <= 10:
        chairs = range(1, 13 + 1)
    elif num <= 15:
        chairs = range(1, 14 + 1)
    elif num <= 20:
        chairs = range(1, 15 + 1)
    elif num == 21:
        chairs = range(1, 16 + 1)
    else:
        chairs = range(1, 8 + 1)
        
    for i in chairs:
        층.append('1층')
        블록.append('C블록')
        열.append(str(num))
        넘버.append(str(i))

In [4]:
# 1층 D블록

total_col = list(range(1,22 + 1))

for num in total_col:
    if num == 1:
        chairs = range(1, 9 + 1)
    elif num <= 5:
        chairs = range(1, 10 + 1)
    elif num <= 10:
        chairs = range(1, 11 + 1)
    elif num <= 14:
        chairs = range(1, 12 + 1)
    elif num == 18:
        chairs = range(1, 13 + 1)
    else:
        chairs = range(1, 14 + 1)
        
    for i in chairs:
        층.append('1층')
        블록.append('D블록')
        열.append(str(num))
        넘버.append(str(i))

In [5]:
# 1층 E 블록

total_col = [1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,21,22]

for num in total_col:
    if num <= 3 or num == 19 :
        chairs = range(1, 9 + 1)
    elif num <= 7 or num == 18:
        chairs = range(1, 10 + 1)
    elif num <= 11 or num == 16 or num == 17:
        chairs = range(1, 11 + 1)
    elif num <= 15:
        chairs = range(1, 12 + 1)
    elif num == 20:
        chairs = range(1, 8 + 1)
    else:
        chairs = range(1, 7 + 1)
        
    for i in chairs:
        층.append('1층')
        블록.append('E블록')
        열.append(str(num))
        넘버.append(str(i))

In [6]:
# 1층 F 블록

total_col = list(range(1,4 + 1))

for num in total_col:
    if num == 1:
        chairs = range(1, 16 + 1)
    elif num == 2:
        chairs = range(1 , 20 + 1)
    elif num == 3:
        chairs = range(1,24 + 1)
    else:
        chairs = range(1, 12 + 1)
        
    for i in chairs:
        층.append('합창석')
        블록.append('F블록')
        열.append(str(num))
        넘버.append(str(i))

In [7]:
# 1층 G블록

total_col = list(range(1,4 + 1))

for num in total_col:
    if num == 1:
        chairs = range(1, 28 + 1)
    elif num == 2:
        chairs = range(1 , 31 + 1)
    elif num == 3:
        chairs = range(1,34 + 1)
    else:
        chairs = range(1, 37 + 1)
        
    for i in chairs:
        층.append('합창석')
        블록.append('G블록')
        열.append(str(num))
        넘버.append(str(i))

In [8]:
# 1층 H 블록

total_col = list(range(1,4 + 1))

for num in total_col:
    if num == 1:
        chairs = range(1, 16 + 1)
    elif num == 2:
        chairs = range(1 , 20 + 1)
    elif num == 3:
        chairs = range(1,24 + 1)
    else:
        chairs = range(1, 12 + 1)
        
    for i in chairs:
        층.append('합창석')
        블록.append('H블록')
        열.append(str(num))
        넘버.append(str(i))

# **2층**

In [9]:
# 2층 A블록

total_col = list(range(1,8 + 1))

for num in total_col:
    if num == 1:
        chairs = range(1, 17 + 1)
    elif num <= 3:
        chairs = range(1, 18 + 1)
    elif num == 4 or num == 6:
        chairs = range(1, 19 + 1)
    elif num == 5:
        chairs = range(1, 20 + 1)
    elif num == 7:
        chairs = range(1, 16 + 1)
    else:
        chairs = range(1, 8 + 1)
        
    for i in chairs:
        층.append('2층')
        블록.append('A블록')
        열.append(str(num))
        넘버.append(str(i))

In [10]:
# 2층 B블록

total_col = list(range(1,8 + 1))

for num in total_col:
    if num == 1:
        chairs = range(1, 9 + 1)
    elif num == 2:
        chairs = range(1, 10 + 1)
    elif num <= 4:
        chairs = range(1, 11 + 1)
    elif num == 5:
        chairs = range(1, 12 + 1)
    elif num == 6:
        chairs = range(1, 13 + 1)
    elif num == 7:
        chairs = range(1, 14 + 1)
    else:
        chairs = range(1, 4 + 1)
        
    for i in chairs:
        층.append('2층')
        블록.append('B블록')
        열.append(str(num))
        넘버.append(str(i))

In [11]:
# 2층 C 블록

total_col = list(range(1,7 + 1))

for num in total_col:
    if num <= 3:
        chairs = range(1, 11 + 1)
    elif num <= 6:
        chairs = range(1, 12 + 1)
    else:
        chairs = range(1, 13 + 1)
        
    for i in chairs:
        층.append('2층')
        블록.append('C블록')
        열.append(str(num))
        넘버.append(str(i))

In [12]:
# 2층 D블록

total_col = list(range(1,8 + 1))

for num in total_col:
    if num == 1:
        chairs = range(1, 9 + 1)
    elif num == 2:
        chairs = range(1, 10 + 1)
    elif num <= 4:
        chairs = range(1, 11 + 1)
    elif num == 5:
        chairs = range(1, 12 + 1)
    elif num == 6:
        chairs = range(1, 13 + 1)
    elif num == 7:
        chairs = range(1, 14 + 1)
    else:
        chairs = range(1, 4 + 1)
        
    for i in chairs:
        층.append('2층')
        블록.append('D블록')
        열.append(str(num))
        넘버.append(str(i))

In [13]:
# 2층 E블록

total_col = list(range(1,8 + 1))

for num in total_col:
    if num == 1:
        chairs = range(1, 17 + 1)
    elif num <= 3:
        chairs = range(1, 18 + 1)
    elif num == 4 or num == 6:
        chairs = range(1, 19 + 1)
    elif num == 5:
        chairs = range(1, 20 + 1)
    elif num == 7:
        chairs = range(1, 16 + 1)
    else:
        chairs = range(1, 8 + 1)
        
    for i in chairs:
        층.append('2층')
        블록.append('E블록')
        열.append(str(num))
        넘버.append(str(i))

In [14]:
# 2층 박스석

total_col = list(range(1,6 + 1))

for num in total_col:
    if num == 1 or num == 6:
        chairs = range(1, 6 + 1)
    elif num == 2 or num == 5:
        chairs = range(1, 8 + 1)
    else:
        chairs = range(1, 10 + 1)
        
    for i in chairs:
        층.append('2층')
        블록.append(f'BOX{num}')
        열.append('없음') # 나중에 붙이는 과정에서 제거하기 편하게 없음으로 맵핑
        넘버.append(str(i))

# **3층**

In [15]:
# 3층 A 블록

total_col = list(range(1, 7 + 1))

for num in total_col:
    if num <= 2 or num == 7:
        chairs = range(1, 5 + 1)
    elif num == 3:
        chairs = range(1, 6 + 1)
    elif num == 4:
        chairs = range(1, 14 + 1)
    elif num == 5:
        chairs = range(1, 12 + 1)
    else:
        chairs = range(1 , 9 + 1)
        
    for i in chairs:
        층.append('3층')
        블록.append('A블록')
        열.append(str(num))
        넘버.append(str(i))

In [16]:
# 3층 B 블록

total_col = list(range(4, 7 + 1))

for num in total_col:
    if num <= 5:
        chairs = range(1, 7 + 1)
    elif num == 6:
        chairs = range(1, 8 + 1)
    else:
        chairs = range(1 , 9 + 1)
        
    for i in chairs:
        층.append('3층')
        블록.append('B블록')
        열.append(str(num))
        넘버.append(str(i))

In [17]:
# 3층 C블록

total_col = list(range(4, 7 + 1))

for num in total_col:
    if num == 4:
        chairs = range(1, 10 + 1)
    elif num == 5:
        chairs = range(1, 11 + 1)
    elif num == 6:
        chairs = range(1, 12 + 1)
    else:
        chairs = range(1 , 13 + 1)
        
    for i in chairs:
        층.append('3층')
        블록.append('C블록')
        열.append(str(num))
        넘버.append(str(i))

In [18]:
# 3층 D블록

total_col = list(range(4, 7 + 1))

for num in total_col:
    if num <= 6:
        chairs = range(1, 12 + 1)
    else:
        chairs = range(1 , 13 + 1)
        
    for i in chairs:
        층.append('3층')
        블록.append('D블록')
        열.append(str(num))
        넘버.append(str(i))

In [19]:
# 3층 E블록

total_col = list(range(4, 7 + 1))

for num in total_col:
    if num == 4:
        chairs = range(1, 10 + 1)
    elif num == 5:
        chairs = range(1, 11 + 1)
    elif num == 6:
        chairs = range(1, 12 + 1)
    else:
        chairs = range(1 , 13 + 1)
        
    for i in chairs:
        층.append('3층')
        블록.append('E블록')
        열.append(str(num))
        넘버.append(str(i))

In [20]:
# 3층 F 블록

total_col = list(range(4, 7 + 1))

for num in total_col:
    if num <= 5:
        chairs = range(1, 7 + 1)
    elif num == 6:
        chairs = range(1, 8 + 1)
    else:
        chairs = range(1 , 9 + 1)
        
    for i in chairs:
        층.append('3층')
        블록.append('F블록')
        열.append(str(num))
        넘버.append(str(i))

In [21]:
# 3층 G 블록

total_col = list(range(1, 7 + 1))

for num in total_col:
    if num <= 2 or num == 7:
        chairs = range(1, 5 + 1)
    elif num == 3:
        chairs = range(1, 6 + 1)
    elif num == 4:
        chairs = range(1, 14 + 1)
    elif num == 5:
        chairs = range(1, 12 + 1)
    else:
        chairs = range(1 , 9 + 1)
        
    for i in chairs:
        층.append('3층')
        블록.append('G블록')
        열.append(str(num))
        넘버.append(str(i))

In [22]:
# 3층 M블록

total_col = [1,2]

for num in total_col:
    for i in range(1 , 15 + 1):
        층.append('3층')
        블록.append('M블록')
        열.append(str(num))
        넘버.append(str(i))

In [23]:
# 3층 N블록

total_col = [1,2]

for num in total_col:
    for i in range(1 , 15 + 1):
        층.append('3층')
        블록.append('N블록')
        열.append(str(num))
        넘버.append(str(i))

In [24]:
# 3층 BOX 석

boxes = [7,8,9,10,11,12]

for num in boxes:
    if num == 7 or num == 10:
        chairs = range(1, 6 + 1)
    elif num == 8 or num == 11:
        chairs = range(1, 9 + 1)
    else:
        chairs = range(1, 4+ 1)
        
    for i in chairs:
        층.append('3층')
        블록.append(f'BOX{num}')
        열.append('없음')
        넘버.append(str(i))

In [25]:
import pandas as pd 

seat_information = pd.DataFrame({'층':층,'블록':블록,'열':열,'넘버':넘버})

seat_information

       층     블록   열 넘버
0     1층    A블록   1  1
1     1층    A블록   1  2
2     1층    A블록   1  3
3     1층    A블록   1  4
4     1층    A블록   1  5
...   ..    ...  .. ..
2482  3층  BOX11  없음  9
2483  3층  BOX12  없음  1
2484  3층  BOX12  없음  2
2485  3층  BOX12  없음  3
2486  3층  BOX12  없음  4

[2487 rows x 4 columns]

In [26]:
블록_열 = seat_information['블록'] + seat_information['열']

seat_information['전체_좌석'] = seat_information['층'] + ' ' + 블록_열 + '열 ' + seat_information['넘버'].astype(str)

seat_information['전체_좌석'] = seat_information['전체_좌석'].str.replace('없음열','') #박스석의 경우엔 박스 넘버가 열 역할을 대신함

In [27]:
seat_information

       층     블록   열 넘버       전체_좌석
0     1층    A블록   1  1  1층 A블록1열 1
1     1층    A블록   1  2  1층 A블록1열 2
2     1층    A블록   1  3  1층 A블록1열 3
3     1층    A블록   1  4  1층 A블록1열 4
4     1층    A블록   1  5  1층 A블록1열 5
...   ..    ...  .. ..         ...
2482  3층  BOX11  없음  9  3층 BOX11 9
2483  3층  BOX12  없음  1  3층 BOX12 1
2484  3층  BOX12  없음  2  3층 BOX12 2
2485  3층  BOX12  없음  3  3층 BOX12 3
2486  3층  BOX12  없음  4  3층 BOX12 4

[2487 rows x 5 columns]

In [28]:
seat_information.to_csv('콘서트홀_좌석정보.csv',index = False)